default_platform(:android)

platform :android do
  desc "Submit a new Internal testing"
  lane :beta do
    gradle(task: "clean")
    gradle(task: "bundle", build_type: 'Release', flavor: "product")
    dirPath = File.expand_path(File.dirname(__FILE__)).chomp('fastlane')
    aabPath = dirPath + "app/build/outputs/bundle/productRelease/app-product-release.aab"
    keyStorePath = dirPath + "Untitled"
    sh("jarsigner", "-verbose", "-sigalg", "SHA1withRSA", "-digestalg", "SHA1", "-keystore", keyStorePath, "-storepass", "123456", "-keypass", "123456", aabPath, "key0")
    upload_to_play_store(track: "internal", release_status: 'draft', aab: aabPath, skip_upload_apk: true)
  end

end
