name: android ci
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "11"
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Unit tests results
        uses: actions/upload-artifact@v3
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDevDebugUnitTest/index.html
  lint:
    name: Lint Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "11"
      - name: Lint debug flavor
        run: bash ./gradlew lintDevDebug --stacktrace
      - name: Lint results
        uses: actions/upload-artifact@v3
        with:
          name: lint
          path: app/build/reports/lint-results-devDebug.html
  ktlint:
    name: Ktlint Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "11"
      - name: Ktlint
        run: bash ./gradlew ktlint --stacktrace 
  codecov:
    name: Code coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "11"
      - name: Code coverage debug flavor
        run: bash ./gradlew testDevDebugUnitTestCoverage --stacktrace
      - name: Code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: app/build/reports/jacoco/testDevDebugUnitTestCoverage/html/    
  apk:
    name: Generate APK
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "11"
      - name: Build debug APK
        run: bash ./gradlew assembleDev --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
  aab:
    name: Generate AAB
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: "11"
      - name: Build debug AAB
        run: bash ./gradlew bundleDev --stacktrace
      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: aab
          path: app/build/outputs/bundle/devDebug/app-dev-debug.aab